// <auto-generated />
using System;
using HotelMarketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HotelMarketplaceDbContext))]
    [Migration("20260719123643_AddTransactionalAuditOutbox")]
    partial class AddTransactionalAuditOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Amenities", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionTimestampUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ActorUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserAccountId");

                    b.HasIndex("HotelId", "ActionTimestampUtc");

                    b.HasIndex("TargetEntityType", "TargetEntityId", "ActionTimestampUtc");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CustomerUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuestFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NoShowAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NoShowReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaymentExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CustomerUserAccountId", "CreatedAtUtc");

                    b.HasIndex("HotelId", "CheckInDate", "CheckOutDate", "Status");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_StayDates", "[CheckOutDate] > [CheckInDate]");

                            t.HasCheckConstraint("CK_Bookings_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.BookingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("BookingRooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingRooms_LineAmount", "[LineAmount] >= 0");

                            t.HasCheckConstraint("CK_BookingRooms_Nights", "[Nights] > 0");

                            t.HasCheckConstraint("CK_BookingRooms_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_BookingRooms_UnitPricePerNight", "[UnitPricePerNight] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.BookingRoomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("AssignedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhysicalRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserAccountId");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingRoomId");

                    b.HasIndex("HotelId", "BookingId");

                    b.HasIndex("PhysicalRoomId", "StartDate", "EndDate", "Status");

                    b.ToTable("BookingRoomAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingRoomAssignments_DateRange", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.CancellationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FreeCancellationHours")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("RefundPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("CancellationPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_CancellationPolicies_FreeCancellationHours", "[FreeCancellationHours] >= 0");

                            t.HasCheckConstraint("CK_CancellationPolicies_RefundPercentage", "[RefundPercentage] >= 0 AND [RefundPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.CommissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("HotelId");

                    b.ToTable("CommissionRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommissionRecords_BaseAmount", "[BaseAmount] >= 0");

                            t.HasCheckConstraint("CK_CommissionRecords_CommissionAmount", "[CommissionAmount] >= 0");

                            t.HasCheckConstraint("CK_CommissionRecords_CommissionRate", "[CommissionRate] >= 0 AND [CommissionRate] <= 0.30");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.GuestStayRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedInAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CheckedInByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckedOutAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("CheckedOutByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuestFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdentityDocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly?>("IdentityExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("IdentityIssuingCountry")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CheckedInByUserAccountId");

                    b.HasIndex("CheckedOutByUserAccountId");

                    b.HasIndex("HotelId", "CheckedInAtUtc");

                    b.ToTable("GuestStayRecords", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("HotelId", "AmenityId")
                        .IsUnique();

                    b.ToTable("HotelAmenities", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "DisplayOrder");

                    b.ToTable("HotelImages", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("DefaultCommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsWalkInEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresRoomInspection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserAccountId");

                    b.HasIndex("City", "ApprovalStatus", "PublicationStatus");

                    b.ToTable("HotelProperties", null, t =>
                        {
                            t.HasCheckConstraint("CK_HotelProperties_DefaultCommissionRate", "[DefaultCommissionRate] >= 0 AND [DefaultCommissionRate] <= 0.30");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelStaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("AssignedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserAccountId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserAccountId", "HotelId", "RoleId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("HotelStaffAssignments", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HousekeepingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhysicalRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserAccountId");

                    b.HasIndex("BookingId");

                    b.HasIndex("PhysicalRoomId");

                    b.HasIndex("HotelId", "Status", "AssignedToUserAccountId");

                    b.ToTable("HousekeepingTasks", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BalanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoomAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("HotelId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_BalanceAmount", "[BalanceAmount] >= 0");

                            t.HasCheckConstraint("CK_Invoices_PaidAmount", "[PaidAmount] >= 0");

                            t.HasCheckConstraint("CK_Invoices_RefundAmount", "[RefundAmount] >= 0");

                            t.HasCheckConstraint("CK_Invoices_RoomAmount", "[RoomAmount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhysicalRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserAccountId");

                    b.HasIndex("PhysicalRoomId");

                    b.HasIndex("ReportedByUserAccountId");

                    b.HasIndex("HotelId", "Status", "AssignedToUserAccountId");

                    b.ToTable("MaintenanceRequests", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RecipientUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserAccountId");

                    b.HasIndex("HotelId", "Status");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.ToTable("NotificationRecords", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PaymentCollectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CollectedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedByUserAccountId");

                    b.HasIndex("HotelId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("BookingId", "Status");

                    b.ToTable("PaymentCollectionRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentCollectionRecords_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GatewayTransactionReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ReconciledAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ReconciliationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("GatewayReference")
                        .IsUnique()
                        .HasFilter("[GatewayReference] IS NOT NULL");

                    b.HasIndex("GatewayTransactionReference")
                        .IsUnique()
                        .HasFilter("[GatewayTransactionReference] IS NOT NULL");

                    b.HasIndex("HotelId", "Status", "ReconciliationStatus");

                    b.ToTable("PaymentTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransactions_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PhysicalRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("HotelId", "RoomNumber")
                        .IsUnique();

                    b.HasIndex("HotelId", "RoomTypeId", "Status");

                    b.ToTable("PhysicalRooms", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RefundRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("HotelId", "Status");

                    b.ToTable("RefundRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefundRecords_ApprovedAmount", "[ApprovedAmount] >= 0 AND [ApprovedAmount] <= [RequestedAmount]");

                            t.HasCheckConstraint("CK_RefundRecords_RequestedAmount", "[RequestedAmount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhysicalRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalRoomId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("HotelId", "RoomTypeId", "StartDate", "EndDate", "Status");

                    b.ToTable("RoomAvailabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomAvailabilities_DateRange", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("ChangedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("PhysicalRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserAccountId");

                    b.HasIndex("HotelId");

                    b.HasIndex("PhysicalRoomId", "ChangedAtUtc");

                    b.ToTable("RoomStatusHistories", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdultCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChildCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "Status");

                    b.ToTable("RoomTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomTypes_AdultCapacity", "[AdultCapacity] > 0");

                            t.HasCheckConstraint("CK_RoomTypes_BasePricePerNight", "[BasePricePerNight] >= 0");

                            t.HasCheckConstraint("CK_RoomTypes_ChildCapacity", "[ChildCapacity] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.SettlementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CommissionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentCollectionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SettlementRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CommissionRecordId");

                    b.HasIndex("HotelId");

                    b.HasIndex("PaymentCollectionRecordId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("SettlementRecordId");

                    b.ToTable("SettlementItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_SettlementItems_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.SettlementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("SettledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettlementDateUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SettlementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasFilter("[Reference] <> ''");

                    b.HasIndex("HotelId", "Status");

                    b.ToTable("SettlementRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_SettlementRecords_ExpectedAmount", "[ExpectedAmount] >= 0");

                            t.HasCheckConstraint("CK_SettlementRecords_SettledAmount", "[SettledAmount] IS NULL OR [SettledAmount] >= 0");
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.StaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("InvitedByUserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserAccountId");

                    b.HasIndex("RoleId");

                    b.HasIndex("HotelId", "Email", "RoleId")
                        .HasFilter("[Status] = 'Active'");

                    b.ToTable("StaffInvitations", (string)null);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("UserAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anonymous-walk-in@system.local",
                            FullName = "Anonymous Walk-in Customer",
                            IsSystemAccount = true,
                            PasswordHash = "LOGIN-DISABLED",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.UserAccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserAccountId", "RoleId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("UserAccountRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222002"),
                            AssignedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111001"),
                            UserAccountId = new Guid("22222222-2222-2222-2222-222222222001")
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            Code = "CUSTOMER",
                            Name = "Customer",
                            Scope = "Customer"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            Code = "PROPERTYOWNER",
                            Name = "Property Owner",
                            Scope = "Hotel"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            Code = "HOTELMANAGER",
                            Name = "Hotel Manager",
                            Scope = "Hotel"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            Code = "RECEPTIONIST",
                            Name = "Receptionist",
                            Scope = "Hotel"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            Code = "HOUSEKEEPINGSTAFF",
                            Name = "Housekeeping Staff",
                            Scope = "Hotel"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111006"),
                            Code = "MAINTENANCESTAFF",
                            Name = "Maintenance Staff",
                            Scope = "Hotel"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111007"),
                            Code = "PLATFORMADMINISTRATOR",
                            Name = "Platform Administrator",
                            Scope = "Platform"
                        });
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.AuditRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Booking", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.BookingRoom", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany("Rooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.BookingRoomAssignment", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.BookingRoom", null)
                        .WithMany()
                        .HasForeignKey("BookingRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PhysicalRoom", null)
                        .WithMany()
                        .HasForeignKey("PhysicalRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.CancellationPolicy", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.CommissionRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.GuestStayRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CheckedInByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CheckedOutByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelAmenity", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany("Amenities")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelImage", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany("Images")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelProperty", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelStaffAssignment", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany("StaffAssignments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HousekeepingTask", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PhysicalRoom", null)
                        .WithMany()
                        .HasForeignKey("PhysicalRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PhysicalRoom", null)
                        .WithMany()
                        .HasForeignKey("PhysicalRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ReportedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.NotificationRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PaymentCollectionRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CollectedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.PhysicalRoom", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany("PhysicalRooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RefundRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomAvailability", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PhysicalRoom", null)
                        .WithMany()
                        .HasForeignKey("PhysicalRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomStatusHistory", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PhysicalRoom", null)
                        .WithMany()
                        .HasForeignKey("PhysicalRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.RoomType", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.SettlementItem", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.CommissionRecord", null)
                        .WithMany()
                        .HasForeignKey("CommissionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.PaymentCollectionRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentCollectionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelMarketplace.Domain.Entities.SettlementRecord", null)
                        .WithMany()
                        .HasForeignKey("SettlementRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.SettlementRecord", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.StaffInvitation", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.HotelProperty", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.UserAccountRole", b =>
                {
                    b.HasOne("HotelMarketplace.Domain.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelMarketplace.Domain.Entities.UserAccount", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.HotelProperty", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("PhysicalRooms");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("HotelMarketplace.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("StaffAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
